server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  sql:
    init:
      platform: postgre
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
  jackson:
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
