server:
  port: 8090
management:
  endpoint.gateway.enabled: true
spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/signIn,/users/signUp
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/fallBack/userService
        - id: user-service
          uri: lb://user-service
          predicates:
            Path=/users/**
          filters:
            - AuthFilter
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:fallback/userService

      filter:
        hystrix:
          enabled: true
    circuitbreaker:
      hystrix:
        enabled: true

  main:
    allow-circular-references: true
    web-application-type: reactive
    allow-bean-definition-overriding: true

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
resilience4j:
  circuitbreaker:
    metrics:
      legacy:
        enabled: true
  bulkhead:
    metrics:
      enabled: true