server:
  port: 8090

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  application.name: gateway-user-auth-service
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/signIn,/users/signUp
        - id: user-service
          uri: lb://user-service
          predicates:
            Path=/users/**
          filters:
            - AuthFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka